// Auto-generated by /rebuild-css-db workflow.  DO NOT EDIT BY HAND.
// Contains raw text of every borders-*.css so standalone CSS export works
// from file:// (where sheet.cssRules is blocked by the same-origin policy).
window.FX_CSS_DB = {
  texts: [
    // ==== borders-01-10.css ====
    `/* ==============================================
   BORDERS 01–10
   ============================================== */

/* 01 — Neon Pulse */
.b01{ border:2px solid #7cf6ff; box-shadow:0 0 0 0 rgba(124,246,255,.6), inset 0 0 18px rgba(124,246,255,.35); animation:b01 1.8s ease-in-out infinite; }
@keyframes b01{
  0%,100%{ box-shadow:0 0 0 0 rgba(124,246,255,.7), 0 0 18px rgba(124,246,255,.5), inset 0 0 14px rgba(124,246,255,.35);}
  50%    { box-shadow:0 0 0 10px rgba(124,246,255,0),  0 0 40px rgba(124,246,255,.9), inset 0 0 28px rgba(124,246,255,.7);}
}

/* 02 — Plasma Arc (conic rotating rim) */
.b02{ position:relative; }
.b02::before{
  content:""; position:absolute; inset:-2px; border-radius:inherit; padding:2px;
  background:conic-gradient(from var(--angle), #ff2bd6, #7c3bff, #00e5ff, #ff2bd6);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  animation:spin-angle 3.5s linear infinite;
  filter:drop-shadow(0 0 10px #7c3bff);
}

/* 03 — Cyber Circuit (dashed marching) */
.b03{ border:2px dashed #62ffb3; animation:b03 .8s linear infinite; box-shadow:inset 0 0 18px rgba(98,255,179,.2),0 0 16px rgba(98,255,179,.25); }
@keyframes b03{ to{ background-position:40px 0; } }
.b03{ background:
  linear-gradient(90deg,#62ffb3 50%,transparent 0) top/16px 2px repeat-x,
  linear-gradient(90deg,#62ffb3 50%,transparent 0) bottom/16px 2px repeat-x,
  linear-gradient(0deg,#62ffb3 50%,transparent 0) left/2px 16px repeat-y,
  linear-gradient(0deg,#62ffb3 50%,transparent 0) right/2px 16px repeat-y;
  border:none;
}

/* 04 — Dragon Fire (flame gradient sweep) */
.b04{ position:relative; }
.b04::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:3px;
  background:conic-gradient(from var(--angle), #ff4500, #ffb300, #ff0000, #ffea00, #ff4500);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:drop-shadow(0 0 14px #ff6a00) blur(.3px);
  animation:spin-angle 2.2s linear infinite;
}
.b04::after{
  content:""; position:absolute; inset:-10px; border-radius:inherit; pointer-events:none;
  background:radial-gradient(closest-side, rgba(255,90,0,.35), transparent 70%);
  animation:pulse-op 1.4s ease-in-out infinite;
}

/* 05 — Holographic Shift */
.b05{ position:relative; }
.b05::before{
  content:""; position:absolute; inset:-2px; border-radius:inherit; padding:2px;
  background:linear-gradient(115deg,#ff6ad5,#c774e8,#ad8cff,#8795e8,#94d0ff);
  background-size:300% 300%;
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  animation:b05 5s linear infinite;
}
@keyframes b05{ 0%{background-position:0% 50%} 100%{background-position:300% 50%} }

/* 06 — Quantum Flux (double counter-rotating rings) */
.b06{ position:relative; }
.b06::before,.b06::after{
  content:""; position:absolute; inset:-4px; border-radius:inherit; padding:2px;
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
}
.b06::before{ background:conic-gradient(from var(--angle), transparent 70%, #00e5ff); animation:spin-angle 2.5s linear infinite; filter:drop-shadow(0 0 8px #00e5ff); }
.b06::after { inset:-10px; background:conic-gradient(from var(--angle), transparent 80%, #ff3bd6); animation:spin-angle 3.8s linear infinite reverse; filter:drop-shadow(0 0 10px #ff3bd6); }

/* 07 — Void Rift (dark cracks pulsing) */
.b07{ border:2px solid #1a1030; box-shadow:inset 0 0 30px #000, 0 0 20px #4b1b8a; position:relative; overflow:hidden; }
.b07::before{
  content:""; position:absolute; inset:0; border-radius:inherit;
  background:
    radial-gradient(2px 30% at 0% 50%, #a36bff, transparent 60%),
    radial-gradient(2px 30% at 100% 50%, #a36bff, transparent 60%),
    radial-gradient(30% 2px at 50% 0%, #a36bff, transparent 60%),
    radial-gradient(30% 2px at 50% 100%, #a36bff, transparent 60%);
  filter:drop-shadow(0 0 6px #a36bff);
  animation:pulse-op 1.6s ease-in-out infinite;
}

/* 08 — Golden Crown (luxury shimmer) */
.b08{ position:relative; }
.b08::before{
  content:""; position:absolute; inset:-2px; border-radius:inherit; padding:2px;
  background:linear-gradient(115deg,#b8862b 0%,#ffe98a 25%,#fff6c0 40%,#ffe98a 55%,#b8862b 100%);
  background-size:200% 200%;
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  animation:b08 3.2s linear infinite;
  filter:drop-shadow(0 0 6px rgba(255,221,120,.5));
}
@keyframes b08{ 0%{background-position:0 0} 100%{background-position:200% 0} }

/* 09 — Blood Oath (dripping crimson) */
.b09{ border:2px solid #6b0f1a; box-shadow:0 0 18px rgba(170,0,20,.55), inset 0 0 16px rgba(255,30,60,.35); position:relative; overflow:visible; }
.b09::after{
  content:""; position:absolute; left:0; right:0; top:100%; height:14px;
  background:
    radial-gradient(6px 14px at 12% 0, #b00020 99%, transparent 100%),
    radial-gradient(5px 10px at 32% 0, #b00020 99%, transparent 100%),
    radial-gradient(7px 18px at 58% 0, #b00020 99%, transparent 100%),
    radial-gradient(4px 9px  at 78% 0, #b00020 99%, transparent 100%),
    radial-gradient(6px 12px at 90% 0, #b00020 99%, transparent 100%);
  animation:b09 2.6s ease-in-out infinite;
  filter:drop-shadow(0 2px 4px rgba(170,0,20,.7));
}
@keyframes b09{ 0%{transform:scaleY(.2);opacity:.6} 60%{transform:scaleY(1.1);opacity:1} 100%{transform:scaleY(.2);opacity:.6} }

/* 10 — Ice Shard (crystalline cold) */
.b10{ border:2px solid #bde8ff; box-shadow:0 0 0 1px #e6f7ff inset, 0 0 24px #6ec6ff, inset 0 0 18px rgba(180,224,255,.6); position:relative; }
.b10::before{
  content:""; position:absolute; inset:-1px; border-radius:inherit; pointer-events:none;
  background:
    linear-gradient(135deg, transparent 40%, rgba(255,255,255,.6) 50%, transparent 60%);
  background-size:250% 250%;
  mix-blend-mode:screen;
  animation:b10 3.4s ease-in-out infinite;
}
@keyframes b10{ 0%{background-position:0 0} 100%{background-position:250% 250%} }
`,

    // ==== borders-101-150.css ====
    `/* ==================================================================
   BORDERS 101–150 — Whole-perimeter "everywhere at once" trail FX
   These reuse the .trail chrome from borders-51-100.css. Per-effect
   panel tints below just pick a background that complements each FX.
   ================================================================== */

/* Warm fire / ember / lava tones */
.b102 .inner,.b103 .inner,.b116 .inner,.b138 .inner,.b142 .inner,.b143 .inner{
  background:linear-gradient(160deg,#120705,#1c0d08);
}

/* Cool ice / water / moon tones */
.b105 .inner,.b106 .inner,.b114 .inner,.b140 .inner,.b149 .inner{
  background:linear-gradient(160deg,#05101a,#0a1a2a);
}
.b115 .inner{ background:linear-gradient(160deg,#061018,#0a1c26); }

/* Electric / plasma / cosmic */
.b104 .inner,.b109 .inner,.b117 .inner,.b123 .inner,.b132 .inner,.b134 .inner,.b150 .inner{
  background:linear-gradient(160deg,#05070e,#0c1228);
}

/* Magic / void / nebula */
.b118 .inner,.b124 .inner,.b127 .inner,.b144 .inner,.b145 .inner{
  background:linear-gradient(160deg,#0a0512,#13092a);
}

/* Nature / forest */
.b119 .inner,.b148 .inner,.b139 .inner,.b130 .inner{
  background:linear-gradient(160deg,#05120a,#081f12);
}

/* Gold / radiant */
.b126 .inner,.b129 .inner{ background:linear-gradient(160deg,#120d02,#1c1504); }

/* Blood / heart */
.b131 .inner,.b146 .inner{ background:linear-gradient(160deg,#140305,#200508); }

/* Sand / ash */
.b121 .inner,.b122 .inner,.b141 .inner{ background:linear-gradient(160deg,#0c0a08,#161310); }

/* Effects that need normal blending (paint, pixel, leaf, petal, feather, confetti, honey) */
.b119 canvas.trail-fx,
.b120 canvas.trail-fx,
.b133 canvas.trail-fx,
.b137 canvas.trail-fx,
.b138 canvas.trail-fx,
.b147 canvas.trail-fx,
.b148 canvas.trail-fx{
  mix-blend-mode:normal;
}

/* Keep meteor / lightning / sparkle on screen blend for bright streaks */
.b101 canvas.trail-fx,
.b104 canvas.trail-fx,
.b117 canvas.trail-fx,
.b125 canvas.trail-fx,
.b134 canvas.trail-fx,
.b142 canvas.trail-fx{
  mix-blend-mode:screen;
}
`,

    // ==== borders-11-20.css ====
    `/* ==============================================
   BORDERS 11–20
   ============================================== */

/* 11 — Electric Storm (jittering bolts) */
.b11{ border:2px solid #bff3ff; box-shadow:0 0 20px #7cf6ff, inset 0 0 14px rgba(124,246,255,.6); animation:b11 .15s steps(2) infinite; }
@keyframes b11{
  0%  { transform:translate(0,0) }
  25% { transform:translate(.6px,-.6px) }
  50% { transform:translate(-.6px,.6px); filter:brightness(1.6) }
  75% { transform:translate(.6px,.6px) }
  100%{ transform:translate(0,0) }
}

/* 12 — Shadow Realm (dark mist seep) */
.b12{ border:2px solid #161824; position:relative; overflow:hidden; }
.b12::before{
  content:""; position:absolute; inset:-40%; border-radius:inherit;
  background:radial-gradient(closest-side, rgba(120,60,200,.55), transparent 70%);
  filter:blur(14px); animation:b12 6s linear infinite;
}
@keyframes b12{ 0%{transform:translate(-20%,-20%) rotate(0)} 100%{transform:translate(20%,20%) rotate(360deg)} }

/* 13 — Phoenix Rising (ember rise) */
.b13{ position:relative; border:2px solid #6b1a00; box-shadow:0 0 20px #ff5a00, inset 0 0 18px rgba(255,120,0,.5); }
.b13::after{
  content:""; position:absolute; inset:-6px -2px -2px -2px; border-radius:inherit; pointer-events:none;
  background:
    radial-gradient(3px 3px at 10% 100%, #ffb347, transparent 60%),
    radial-gradient(2px 2px at 25% 100%, #ff7a00, transparent 60%),
    radial-gradient(3px 3px at 45% 100%, #ffd27a, transparent 60%),
    radial-gradient(2px 2px at 65% 100%, #ff7a00, transparent 60%),
    radial-gradient(3px 3px at 85% 100%, #ffb347, transparent 60%);
  animation:b13 2s linear infinite;
}
@keyframes b13{ 0%{transform:translateY(0);opacity:.2} 50%{opacity:1} 100%{transform:translateY(-24px);opacity:0} }

/* 14 — Nebula Dust */
.b14{ position:relative; }
.b14::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:3px;
  background:conic-gradient(from var(--angle),#3a2a7c,#ff5ea8,#6fe0ff,#9b5cff,#3a2a7c);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:blur(.3px) drop-shadow(0 0 8px #9b5cff);
  animation:spin-angle 8s linear infinite;
}

/* 15 — Energy Shield (hex scan) */
.b15{ border:2px solid #66ffd1; box-shadow:0 0 16px #66ffd1, inset 0 0 18px rgba(102,255,209,.35); position:relative; overflow:hidden; }
.b15::before{
  content:""; position:absolute; left:-50%; right:-50%; top:-2px; height:6px;
  background:linear-gradient(90deg,transparent,#b6fff0,transparent);
  animation:b15 2.2s linear infinite;
}
@keyframes b15{ 0%{transform:translateY(0)} 100%{transform:translateY(var(--sq))} }

/* 16 — Chromatic Pulse (RGB split) */
.b16{ position:relative; border:2px solid #fff; }
.b16{ box-shadow:
  -4px 0 0 #ff2a6d, 4px 0 0 #05d9e8, 0 -4px 0 #ff2a6d, 0 4px 0 #05d9e8,
  0 0 18px rgba(255,255,255,.25);
  animation:b16 1.4s ease-in-out infinite; }
@keyframes b16{ 0%,100%{filter:none} 50%{filter:blur(.6px) saturate(1.6)} }

/* 17 — Runic Seal (etched glow) */
.b17{ border:3px double #d9b26a; box-shadow:0 0 18px rgba(217,178,106,.55), inset 0 0 14px rgba(217,178,106,.35); position:relative; }
.b17::before{
  content:""; position:absolute; inset:4px; border:1px solid rgba(217,178,106,.5); border-radius:calc(var(--radius) - 6px);
  animation:pulse-op 2.4s ease-in-out infinite;
}

/* 18 — Laser Grid */
.b18{ position:relative; border:1px solid rgba(0,255,170,.4); box-shadow:0 0 14px rgba(0,255,170,.45); }
.b18::before{
  content:""; position:absolute; inset:0; border-radius:inherit; pointer-events:none;
  background:
    linear-gradient(90deg, rgba(0,255,170,.5) 1px, transparent 1px) 0 0/20px 100%,
    linear-gradient(0deg,  rgba(0,255,170,.5) 1px, transparent 1px) 0 0/100% 20px;
  mask:linear-gradient(#000,#000);
  animation:b18 2s linear infinite;
}
@keyframes b18{ to{ background-position:20px 0, 0 20px; } }

/* 19 — Toxic Sludge (bubbling acid) */
.b19{ border:2px solid #7dff2a; box-shadow:0 0 18px #7dff2a, inset 0 0 16px rgba(125,255,42,.4); position:relative; }
.b19::after{
  content:""; position:absolute; inset:-2px; border-radius:inherit; pointer-events:none;
  background:
    radial-gradient(6px 6px at 20% 100%, #d7ff7d, transparent 60%),
    radial-gradient(5px 5px at 50% 100%, #a8ff5e, transparent 60%),
    radial-gradient(7px 7px at 80% 100%, #7dff2a, transparent 60%);
  animation:b19 2.6s ease-in-out infinite;
}
@keyframes b19{ 0%{transform:translateY(0);opacity:.2} 50%{opacity:.9} 100%{transform:translateY(-18px);opacity:0} }

/* 20 — Celestial Aura (halo rings) */
.b20{ position:relative; border:1px solid #fff8c4; box-shadow:0 0 18px #fff0a0, inset 0 0 12px rgba(255,240,160,.45); }
.b20::before,.b20::after{
  content:""; position:absolute; inset:-6px; border-radius:inherit; border:1px solid rgba(255,240,160,.6); pointer-events:none;
  animation:b20 2.8s ease-out infinite;
}
.b20::after{ animation-delay:1.4s; }
@keyframes b20{ 0%{transform:scale(1);opacity:.9} 100%{transform:scale(1.25);opacity:0} }
`,

    // ==== borders-21-30.css ====
    `/* ==============================================
   BORDERS 21–30
   ============================================== */

/* 21 — Magma Core */
.b21{ position:relative; border:2px solid #3a0a00; box-shadow:0 0 22px #ff3d00, inset 0 0 18px rgba(255,80,0,.55); }
.b21::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:3px;
  background:conic-gradient(from var(--angle),#3a0a00,#ff3d00,#ffb300,#ff3d00,#3a0a00);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  animation:spin-angle 4s linear infinite; filter:drop-shadow(0 0 10px #ff6a00);
}

/* 22 — Arctic Frost (creeping frost) */
.b22{ border:2px solid #cfefff; box-shadow:inset 0 0 18px rgba(200,235,255,.6), 0 0 18px #7ac7ff; position:relative; overflow:hidden; }
.b22::before{
  content:""; position:absolute; inset:0; border-radius:inherit;
  background:
    radial-gradient(circle at 0 0, rgba(255,255,255,.7), transparent 30%),
    radial-gradient(circle at 100% 100%, rgba(200,235,255,.7), transparent 30%);
  mix-blend-mode:screen; animation:b22 4s ease-in-out infinite alternate;
}
@keyframes b22{ 0%{opacity:.4} 100%{opacity:1} }

/* 23 — Spectral Mist */
.b23{ border:2px solid #b0a7ff; box-shadow:0 0 22px #8a7cff, inset 0 0 18px rgba(180,170,255,.45); position:relative; overflow:hidden; }
.b23::after{
  content:""; position:absolute; inset:-30%; border-radius:50%;
  background:radial-gradient(closest-side, rgba(180,170,255,.7), transparent 70%);
  filter:blur(10px); animation:b23 5s linear infinite;
}
@keyframes b23{ 0%{transform:translate(-20%,0)} 100%{transform:translate(20%,-10%)} }

/* 24 — Crystal Lattice */
.b24{ position:relative; border:2px solid #b5e3ff; box-shadow:0 0 16px #8ec8ff, inset 0 0 14px rgba(181,227,255,.45); }
.b24::before{
  content:""; position:absolute; inset:-1px; border-radius:inherit; pointer-events:none;
  background:
    linear-gradient(45deg, rgba(255,255,255,.5) 25%, transparent 25%) 0 0/10px 10px,
    linear-gradient(-45deg, rgba(255,255,255,.5) 25%, transparent 25%) 0 0/10px 10px;
  mix-blend-mode:screen; opacity:.5;
  animation:b24 4s linear infinite;
}
@keyframes b24{ to{background-position:10px 0,10px 0} }

/* 25 — Warp Drive (hyperspace streaks) */
.b25{ position:relative; border:1px solid #8be9ff; box-shadow:0 0 20px #8be9ff; overflow:hidden; }
.b25::before{
  content:""; position:absolute; inset:-2px; border-radius:inherit;
  background:
    linear-gradient(90deg,transparent 0,#8be9ff 50%,transparent 100%) 0 20%/200% 2px no-repeat,
    linear-gradient(90deg,transparent 0,#bffaff 50%,transparent 100%) 0 50%/200% 2px no-repeat,
    linear-gradient(90deg,transparent 0,#8be9ff 50%,transparent 100%) 0 80%/200% 2px no-repeat;
  animation:b25 1.2s linear infinite;
}
@keyframes b25{ 0%{background-position:-100% 20%,-150% 50%,-80% 80%} 100%{background-position:200% 20%,220% 50%,260% 80%} }

/* 26 — Demonic Sigil */
.b26{ position:relative; border:2px solid #3a0010; box-shadow:0 0 22px #ff003c, inset 0 0 16px rgba(255,0,60,.55); }
.b26::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:3px;
  background:conic-gradient(from var(--angle),#ff003c,#3a0010,#ff003c,#3a0010,#ff003c);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  animation:spin-angle 6s linear infinite reverse; filter:drop-shadow(0 0 8px #ff003c);
}

/* 27 — Aurora Borealis */
.b27{ position:relative; }
.b27::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:3px;
  background:linear-gradient(120deg,#00ffa3,#00b3ff,#b84cff,#00ffa3);
  background-size:300% 300%;
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:blur(.4px) drop-shadow(0 0 10px #00ffa3);
  animation:b27 6s ease-in-out infinite;
}
@keyframes b27{ 0%,100%{background-position:0 50%} 50%{background-position:100% 50%} }

/* 28 — Sonic Wave (expanding rings) */
.b28{ position:relative; border:2px solid #fff; box-shadow:0 0 12px #fff; }
.b28::before,.b28::after{
  content:""; position:absolute; inset:0; border-radius:inherit; border:2px solid rgba(255,255,255,.7);
  animation:b28 2.2s ease-out infinite;
}
.b28::after{ animation-delay:1.1s; }
@keyframes b28{ 0%{transform:scale(1);opacity:1} 100%{transform:scale(1.35);opacity:0} }

/* 29 — Molten Gold */
.b29{ position:relative; }
.b29::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:3px;
  background:linear-gradient(115deg,#8a5a00,#ffd56a,#fff2b3,#ffd56a,#8a5a00);
  background-size:300% 100%;
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:drop-shadow(0 0 10px rgba(255,213,106,.6));
  animation:b29 3s linear infinite;
}
@keyframes b29{ to{background-position:300% 0} }

/* 30 — Radioactive (geiger blink) */
.b30{ border:2px solid #d6ff00; box-shadow:0 0 18px #d6ff00, inset 0 0 14px rgba(214,255,0,.45); animation:b30 1s steps(3,end) infinite; position:relative; }
.b30::after{
  content:"☢"; position:absolute; top:6px; right:8px; color:#d6ff00; font-size:.9rem; text-shadow:0 0 8px #d6ff00; opacity:.9;
}
@keyframes b30{ 0%,100%{filter:brightness(1)} 33%{filter:brightness(1.6)} 66%{filter:brightness(.85)} }
`,

    // ==== borders-31-40.css ====
    `/* ==============================================
   BORDERS 31–40
   ============================================== */

/* 31 — Starlight (twinkle dots) */
.b31{ border:1px solid rgba(255,255,255,.25); box-shadow:inset 0 0 14px rgba(255,255,255,.08); position:relative; overflow:hidden; }
.b31::before{
  content:""; position:absolute; inset:0; border-radius:inherit;
  background:
    radial-gradient(1px 1px at 10% 20%, #fff 99%, transparent 100%),
    radial-gradient(1px 1px at 25% 70%, #fff 99%, transparent 100%),
    radial-gradient(1.5px 1.5px at 60% 15%, #fff 99%, transparent 100%),
    radial-gradient(1px 1px at 80% 60%, #fff 99%, transparent 100%),
    radial-gradient(1.5px 1.5px at 40% 85%, #fff 99%, transparent 100%),
    radial-gradient(1px 1px at 92% 30%, #fff 99%, transparent 100%);
  animation:b31 2.4s ease-in-out infinite alternate;
}
@keyframes b31{ 0%{opacity:.2;filter:blur(0)} 100%{opacity:1;filter:blur(.4px)} }

/* 32 — Binary Stream */
.b32{ position:relative; border:1px solid #00ff88; box-shadow:0 0 16px #00ff88; overflow:hidden; color:#00ff88; font:700 10px/1 monospace; }
.b32::before{
  content:"01001000 01010100 01000001 01001110 01000110 01010100 10101010 11001100 00110011";
  position:absolute; inset:-2px; border-radius:inherit; padding:4px; letter-spacing:1px;
  white-space:pre-wrap; word-break:break-all; opacity:.85; text-shadow:0 0 4px #00ff88;
  animation:b32 4s linear infinite;
}
@keyframes b32{ 0%{transform:translateY(0)} 100%{transform:translateY(-24px)} }

/* 33 — Blood Moon */
.b33{ border:2px solid #2a0008; box-shadow:0 0 22px #ff1744, inset 0 0 14px rgba(255,23,68,.55); animation:b33 2.6s ease-in-out infinite; }
@keyframes b33{ 0%,100%{box-shadow:0 0 14px #9e0022, inset 0 0 12px rgba(255,23,68,.35)} 50%{box-shadow:0 0 36px #ff1744, inset 0 0 22px rgba(255,23,68,.75)} }

/* 34 — Venom Strike */
.b34{ position:relative; border:2px solid #062a10; box-shadow:0 0 18px #21d07a, inset 0 0 12px rgba(33,208,122,.5); }
.b34::before{
  content:""; position:absolute; inset:-2px; border-radius:inherit; padding:2px;
  background:conic-gradient(from var(--angle),#062a10,#21d07a 20%,#c6ff6a 30%,#21d07a 40%,#062a10 60%);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  animation:spin-angle 2.4s linear infinite;
}

/* 35 — Ethereal Wisp */
.b35{ position:relative; border:1px solid rgba(200,220,255,.35); box-shadow:inset 0 0 18px rgba(170,200,255,.3); overflow:hidden; }
.b35::before{
  content:""; position:absolute; inset:-40%; border-radius:50%;
  background:radial-gradient(closest-side, rgba(190,210,255,.6), transparent 70%);
  filter:blur(14px); animation:b35 7s ease-in-out infinite;
}
@keyframes b35{ 0%{transform:translate(-20%,-10%)} 50%{transform:translate(20%,10%)} 100%{transform:translate(-20%,-10%)} }

/* 36 — Thunder Strike */
.b36{ border:2px solid #e1f3ff; box-shadow:0 0 16px #bae0ff, inset 0 0 12px rgba(186,224,255,.4); animation:b36 4s linear infinite; }
@keyframes b36{
  0%,90%,100%{ filter:brightness(1); }
  92% { filter:brightness(3) saturate(2); }
  94% { filter:brightness(.7); }
  96% { filter:brightness(2.5); }
}

/* 37 — Crystal Growth (animated facets) */
.b37{ position:relative; border:2px solid #c8b6ff; box-shadow:0 0 18px #9a7bff, inset 0 0 14px rgba(200,182,255,.45); }
.b37::before{
  content:""; position:absolute; inset:-2px; border-radius:inherit; pointer-events:none;
  background:
    linear-gradient(60deg, transparent 46%, #e3d9ff 48%, transparent 52%),
    linear-gradient(-60deg, transparent 46%, #c8b6ff 48%, transparent 52%);
  background-size:18px 18px;
  mix-blend-mode:screen; opacity:.7;
  animation:b37 5s linear infinite;
}
@keyframes b37{ to{background-position:18px 0, -18px 0} }

/* 38 — Smoke Veil */
.b38{ position:relative; border:1px solid rgba(255,255,255,.15); box-shadow:inset 0 0 20px rgba(180,180,180,.3); overflow:hidden; }
.b38::before{
  content:""; position:absolute; inset:-50%; border-radius:50%;
  background:radial-gradient(closest-side, rgba(200,200,210,.55), transparent 70%);
  filter:blur(18px); animation:b38 9s linear infinite;
}
@keyframes b38{ 0%{transform:translate(-15%,-15%) rotate(0)} 100%{transform:translate(15%,15%) rotate(360deg)} }

/* 39 — Prismatic Edge */
.b39{ position:relative; }
.b39::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:3px;
  background:conic-gradient(from var(--angle),red,orange,yellow,lime,cyan,blue,magenta,red);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:drop-shadow(0 0 8px rgba(255,255,255,.4));
  animation:spin-angle 4s linear infinite;
}

/* 40 — Stealth Cloak (invisible flicker) */
.b40{ border:1px dashed rgba(255,255,255,.18); box-shadow:inset 0 0 14px rgba(255,255,255,.06); animation:b40 3s ease-in-out infinite; position:relative; }
.b40::before{
  content:""; position:absolute; inset:-1px; border-radius:inherit;
  background:linear-gradient(120deg, transparent 40%, rgba(255,255,255,.35) 50%, transparent 60%);
  background-size:250% 250%;
  animation:b40b 3s linear infinite;
  mix-blend-mode:screen; pointer-events:none;
}
@keyframes b40 { 0%,100%{opacity:.7} 50%{opacity:.25} }
@keyframes b40b{ 0%{background-position:0 0} 100%{background-position:250% 250%} }
`,

    // ==== borders-41-50.css ====
    `/* ==============================================
   BORDERS 41–50
   ============================================== */

/* 41 — Sacred Flame */
.b41{ position:relative; border:2px solid #fff0b3; box-shadow:0 0 22px #ffd95a, inset 0 0 14px rgba(255,217,90,.55); }
.b41::before{
  content:""; position:absolute; inset:-4px; border-radius:inherit; padding:3px;
  background:conic-gradient(from var(--angle),#fff0b3,#ffd95a,#ffb347,#fff0b3);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:drop-shadow(0 0 10px #ffd95a);
  animation:spin-angle 5s linear infinite;
}
.b41::after{
  content:""; position:absolute; inset:-14px; border-radius:inherit;
  background:radial-gradient(closest-side, rgba(255,217,90,.3), transparent 70%);
  animation:pulse-op 2s ease-in-out infinite; pointer-events:none;
}

/* 42 — Glitch Matrix */
.b42{ border:2px solid #00ffcc; position:relative; box-shadow:0 0 14px #00ffcc, inset 0 0 10px rgba(0,255,204,.35); animation:b42 1.6s steps(6) infinite; }
.b42::before,.b42::after{
  content:""; position:absolute; inset:0; border-radius:inherit; pointer-events:none;
  border:2px solid transparent;
}
.b42::before{ border-color:#ff2ac3; transform:translate(2px,0); mix-blend-mode:screen; animation:b42a 1.6s steps(6) infinite; }
.b42::after { border-color:#2affc3; transform:translate(-2px,0); mix-blend-mode:screen; animation:b42b 1.6s steps(6) infinite; }
@keyframes b42 { 0%,100%{clip-path:inset(0)} 30%{clip-path:inset(12% 0 40% 0)} 60%{clip-path:inset(50% 0 10% 0)} }
@keyframes b42a{ 0%,100%{transform:translate(2px,0)} 40%{transform:translate(-3px,1px)} 70%{transform:translate(4px,-2px)} }
@keyframes b42b{ 0%,100%{transform:translate(-2px,0)} 40%{transform:translate(3px,-1px)} 70%{transform:translate(-4px,2px)} }

/* 43 — Acid Etch (corroding edge) */
.b43{ border:2px solid #b6ff3a; box-shadow:0 0 18px #b6ff3a, inset 0 0 14px rgba(182,255,58,.35); position:relative; }
.b43::before{
  content:""; position:absolute; inset:-2px; border-radius:inherit; padding:2px;
  background:repeating-linear-gradient(45deg,#b6ff3a 0 6px,transparent 6px 12px);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  animation:b43 1.2s linear infinite;
}
@keyframes b43{ to{background-position:12px 0} }

/* 44 — Stardust Trail (drawn via JS canvas overlay fallback: CSS particles) */
.b44{ position:relative; border:1px solid rgba(255,255,255,.25); box-shadow:inset 0 0 12px rgba(255,255,255,.12); overflow:hidden; }
.b44::before{
  content:""; position:absolute; inset:-2px; border-radius:inherit;
  background:
    radial-gradient(2px 2px at 10% 50%, #fff, transparent 60%),
    radial-gradient(1.5px 1.5px at 30% 50%, #b3e5ff, transparent 60%),
    radial-gradient(1px 1px at 60% 50%, #fff, transparent 60%),
    radial-gradient(1.5px 1.5px at 85% 50%, #ffd5f2, transparent 60%);
  animation:b44 3s linear infinite;
  filter:drop-shadow(0 0 6px rgba(255,255,255,.7));
}
@keyframes b44{ 0%{transform:translateX(-30%)} 100%{transform:translateX(30%)} }

/* 45 — Chronos Ring (ticking) */
.b45{ position:relative; border:2px solid #c9d6ff; box-shadow:0 0 16px #8aa0ff, inset 0 0 10px rgba(201,214,255,.4); }
.b45::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:2px;
  background:conic-gradient(from 0deg,#c9d6ff 0 15deg, transparent 15deg 360deg);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  animation:b45 6s steps(12) infinite;
}
@keyframes b45{ to{ transform:rotate(360deg) } }

/* 46 — Diamond Cut (faceted sparkle) */
.b46{ position:relative; border:2px solid #e7f0ff; box-shadow:0 0 16px #cfe0ff, inset 0 0 10px rgba(231,240,255,.6); }
.b46::before{
  content:""; position:absolute; inset:-1px; border-radius:inherit; pointer-events:none;
  background:linear-gradient(135deg, transparent 44%, rgba(255,255,255,.95) 50%, transparent 56%);
  background-size:250% 250%;
  mix-blend-mode:screen;
  animation:b46 2.2s linear infinite;
}
@keyframes b46{ 0%{background-position:0 0} 100%{background-position:250% 250%} }

/* 47 — Mystic Scroll (runes scrolling) */
.b47{ position:relative; border:2px solid #6a4bff; box-shadow:0 0 18px #6a4bff, inset 0 0 14px rgba(106,75,255,.4); color:#c7b8ff; font:700 10px/1 "Segoe UI Symbol",sans-serif; overflow:hidden; }
.b47::before{
  content:"ᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁᛃᛇᛈᛉᛊᛏᛒᛖᛗᛚᛜᛞᛟᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁ";
  position:absolute; left:0; right:0; padding:3px 6px; letter-spacing:3px;
  text-shadow:0 0 6px #6a4bff; opacity:.85;
  animation:b47 8s linear infinite;
}
@keyframes b47{ 0%{transform:translateX(0)} 100%{transform:translateX(-50%)} }

/* 48 — Inferno Ring */
.b48{ position:relative; }
.b48::before{
  content:""; position:absolute; inset:-4px; border-radius:inherit; padding:4px;
  background:conic-gradient(from var(--angle),#ff0000,#ff7a00,#ffd000,#ff7a00,#ff0000);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:blur(.6px) drop-shadow(0 0 14px #ff4000);
  animation:spin-angle 1.8s linear infinite;
}
.b48::after{
  content:""; position:absolute; inset:-16px; border-radius:inherit;
  background:radial-gradient(closest-side, rgba(255,90,0,.35), transparent 70%);
  animation:pulse-op 1.2s ease-in-out infinite; pointer-events:none;
}

/* 49 — Liquid Metal (chrome flow) */
.b49{ position:relative; }
.b49::before{
  content:""; position:absolute; inset:-3px; border-radius:inherit; padding:3px;
  background:linear-gradient(115deg,#3a3f4a,#c9d0dc 25%,#ffffff 45%,#9aa3b4 60%,#3a3f4a 100%);
  background-size:300% 100%;
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:drop-shadow(0 0 8px rgba(255,255,255,.3));
  animation:b49 4s linear infinite;
}
@keyframes b49{ to{background-position:300% 0} }

/* 50 — Apex Legend (signature multi-layer hero border) */
.b50{ position:relative; }
.b50::before{
  content:""; position:absolute; inset:-4px; border-radius:inherit; padding:3px;
  background:conic-gradient(from var(--angle),#ff2bd6,#7c3bff,#00e5ff,#00ffa3,#ffd000,#ff2bd6);
  -webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
          mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);
  -webkit-mask-composite:xor; mask-composite:exclude;
  filter:drop-shadow(0 0 12px rgba(124,59,255,.7));
  animation:spin-angle 6s linear infinite;
}
.b50::after{
  content:""; position:absolute; inset:-14px; border-radius:inherit; pointer-events:none;
  background:
    radial-gradient(closest-side, rgba(124,59,255,.35), transparent 70%),
    radial-gradient(closest-side, rgba(0,229,255,.25), transparent 70%);
  background-size:100% 100%, 80% 80%;
  background-position:center, center;
  animation:pulse-op 2.2s ease-in-out infinite;
}
.b50 .inner{
  background:
    linear-gradient(160deg,#0f1220,#1a1f33) padding-box,
    conic-gradient(from 0deg, #00e5ff, #ff2bd6, #00e5ff) border-box;
  border:1px solid transparent;
}
`,

    // ==== borders-51-100.css ====
    `/* ==================================================================
   BORDERS 51–100 — Mouse-trail-inspired effects running on the border
   All of these are canvas-driven. The .trail class provides the base
   chrome (thin rim + inner content panel); the JS engine (trail.js)
   paints the animated perimeter on top.
   ================================================================== */

.trail{
  position:relative;
  border:1px solid rgba(255,255,255,.08);
  box-shadow:inset 0 0 20px rgba(0,0,0,.55);
  overflow:hidden;
  isolation:isolate;
}
.trail canvas.trail-fx{
  position:absolute; inset:0;
  width:100%; height:100%;
  border-radius:inherit;
  pointer-events:none;
  z-index:2;
  mix-blend-mode:screen;
}

/* A few per-effect tints on the inner panel for variety */
.b51 .inner,.b53 .inner,.b63 .inner,.b67 .inner,.b89 .inner,.b94 .inner,.b100 .inner{
  background:linear-gradient(160deg,#05070e,#0c1228);
}
.b55 .inner,.b65 .inner,.b77 .inner,.b78 .inner{
  background:linear-gradient(160deg,#0b0814,#120a1e);
}
.b56 .inner,.b79 .inner,.b85 .inner,.b99 .inner{
  background:linear-gradient(160deg,#140806,#1e0c08);
}
.b60 .inner,.b61 .inner,.b69 .inner,.b96 .inner{
  background:linear-gradient(160deg,#061018,#0a1a28);
}
.b95 .inner{ background:linear-gradient(160deg,#05140a,#082012); }
.b68 .inner{ background:linear-gradient(160deg,#180614,#220a1e); }

/* Some effects look better with no screen blend (ink, paint, pixel) */
.b55 canvas.trail-fx,
.b65 canvas.trail-fx,
.b66 canvas.trail-fx,
.b82 canvas.trail-fx,
.b83 canvas.trail-fx,
.b84 canvas.trail-fx,
.b87 canvas.trail-fx{
  mix-blend-mode:normal;
}
`,

  ]
};

